blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
	path('index', views.index, name='index'),
	path('about-me', views.aboutMe, name='about-me'),
	path('journal', views.journal, name='journal'),
	path('resume', views.resume, name='resume'),
	path('contact', views.contact, name='contact'),
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
	blog_title = models.CharField(max_length=50)
	pub_date = models.DateTimeField('date published')
	author_name = models.CharField(max_length=50)
	content = models.TextField()

class Comment(models.Model):
	blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
	pub_date = models.DateTimeField('date published')
	author_nickname = models.CharField(max_length=50)
	author_email = models.CharField(max_length=50)
	content = models.TextField()

blog/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from time import strftime
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from .models import Blog, Comment

# Create your views here.
def index(request):
	context = {
		'now': strftime("%m/%d/%Y"),
	}
	return render(request, 'blog/index.html', context)

def aboutMe(request):
	context = {
		'now': strftime("%m/%d/%Y"),
	}
	return render(request, 'blog/about-me.html', context)

def journal(request):
	context = {
		'now': strftime("%m/%d/%Y"),
	}
	return render(request, 'blog/journal.html', context)

def resume(request):
	context = {
		'now': strftime("%m/%d/%Y"),
	}
	return render(request, 'blog/resume.html', context)

def contact(request):
	context = {
		'now': strftime("%m/%d/%Y"),
	}
	return render(request, 'blog/contact.html', context)

blog/templates/blog/about-me.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'blog/blogStyle.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Jason's Blog</a>
                <p class="Time navbar-text"> {{ now }} </p>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'blog:index' %}">Home</a></li>
                <li class="active"><a href="{% url 'blog:about-me' %}">About Me</a></li>
                <li><a href="{% url 'blog:journal' %}">Journal</a></li>
                <li><a href="{% url 'blog:resume' %}">Resume</a></li>
				<li><a href="{% url 'blog:contact' %}">Say Hello</a></li>
            </ul>
        </div>
    </nav>

	<div class="container">
		<h1 class="text-center">Welcome to the About Me Page.</h1>
	</div>

</body>
</html>

blog/templates/blog/contact.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'blog/blogStyle.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Jason's Blog</a>
                <p class="Time navbar-text"> {{ now }} </p>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'blog:about-me' %}">About Me</a></li>
                <li><a href="{% url 'blog:journal' %}">Journal</a></li>
                <li><a href="{% url 'blog:resume' %}">Resume</a></li>
				<li class="active"><a href="{% url 'blog:contact' %}">Say Hello</a></li>
            </ul>
        </div>
    </nav>

	<div class="container">
		<h1 class="text-center">Welcome to the Contact Page.</h1>
	</div>

</body>
</html>

blog/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'blog/blogStyle.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<link rel="icon" href="{% static favicon.ico %}">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Jason's Blog</a>
                <p class="Time navbar-text"> {{ now }} </p>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'blog:about-me' %}">About Me</a></li>
                <li><a href="{% url 'blog:journal' %}">Journal</a></li>
                <li><a href="{% url 'blog:resume' %}">Resume</a></li>
				<li><a href="{% url 'blog:contact' %}">Say Hello</a></li>
            </ul>
        </div>
    </nav>

	<div class="container">
		<h1 class="text-center">Welcome to the Home page.</h1>
		<br>
	</div>

	<div>
		{% if blog_list %}
			{% for blog in blog_list %}
				<div class="container" id="HomeBlog">
						<a href="{% url 'blog:entry' blog.id %}"><h2>{{ blog.blog_title }}</h2></a>
						<h4>{{ blog.author_name }}, Comments: {{ blog.comment_set.count }}</h4>
						<p class="Paragraph">{{ blog.content|truncatewords:200 }}</p>
				</div>
				<br>
			{% endfor %}
		{% else %}
			<p>No blogs are available.</p>
		{% endif %}
	</div>

</body>
</html>

blog/templates/blog/journal.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'blog/blogStyle.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Jason's Blog</a>
                <p class="Time navbar-text"> {{ now }} </p>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'blog:about-me' %}">About Me</a></li>
                <li class="active"><a href="{% url 'blog:journal' %}">Journal</a></li>
                <li><a href="{% url 'blog:resume' %}">Resume</a></li>
				<li><a href="{% url 'blog:contact' %}">Say Hello</a></li>
            </ul>
        </div>
    </nav>

	<div class="container">
		<h1 class="text-center">Welcome to the Journal.</h1>
	</div>

</body>
</html>

blog/templates/blog/resume.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'blog/blogStyle.css' %}">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-light">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'blog:index' %}">Jason's Blog</a>
                <p class="Time navbar-text"> {{ now }} </p>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'blog:index' %}">Home</a></li>
                <li><a href="{% url 'blog:about-me' %}">About Me</a></li>
                <li><a href="{% url 'blog:journal' %}">Journal</a></li>
                <li class="active"><a href="{% url 'blog:resume' %}">Resume</a></li>
				<li><a href="{% url 'blog:contact' %}">Say Hello</a></li>
            </ul>
        </div>
    </nav>

	<div class="container">
		<h1 class="text-center">Welcome to my Resume.</h1>
	</div>

</body>
</html>